import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import TanstackProvider from '@/config/TanstackProvider';
import Footer from '@/components/template/Footer';
import Navbar from '@/components/template/Navbar';
import FullScreenLoader from '@/components/template/FullScreenLoader';
import AppWrapper from '@/config/AppWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AppWrapper>
          <div className='flex min-h-screen flex-col justify-between bg-global-bg'>
            <FullScreenLoader />
            <TanstackProvider>
              <Navbar />
              {children}
              <Footer />
            </TanstackProvider>
          </div>
        </AppWrapper>
      </body>
    </html>
  );
}
